/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as R404RouteImport } from './routes/404'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AppHomeHomeLayoutRouteImport } from './routes/app/home/_homeLayout'
import { Route as AppHomeHomeLayoutIndexRouteImport } from './routes/app/home/_homeLayout/index'
import { Route as AppHomeHomeLayoutServiceRouteImport } from './routes/app/home/_homeLayout/service'
import { Route as AppHomeHomeLayoutAboutRouteImport } from './routes/app/home/_homeLayout/about'
import { Route as LayoutAppPostsPostIdRouteImport } from './routes/_layout/app/posts/$postId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AppHomeHomeLayoutRoute = AppHomeHomeLayoutRouteImport.update({
  id: '/app/home/_homeLayout',
  path: '/app/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeHomeLayoutIndexRoute = AppHomeHomeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHomeHomeLayoutRoute,
} as any)
const AppHomeHomeLayoutServiceRoute =
  AppHomeHomeLayoutServiceRouteImport.update({
    id: '/service',
    path: '/service',
    getParentRoute: () => AppHomeHomeLayoutRoute,
  } as any)
const AppHomeHomeLayoutAboutRoute = AppHomeHomeLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppHomeHomeLayoutRoute,
} as any)
const LayoutAppPostsPostIdRoute = LayoutAppPostsPostIdRouteImport.update({
  id: '/app/posts/$postId',
  path: '/app/posts/$postId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/404': typeof R404Route
  '/': typeof LayoutIndexRoute
  '/app/home': typeof AppHomeHomeLayoutRouteWithChildren
  '/app/posts/$postId': typeof LayoutAppPostsPostIdRoute
  '/app/home/about': typeof AppHomeHomeLayoutAboutRoute
  '/app/home/service': typeof AppHomeHomeLayoutServiceRoute
  '/app/home/': typeof AppHomeHomeLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/': typeof LayoutIndexRoute
  '/app/posts/$postId': typeof LayoutAppPostsPostIdRoute
  '/app/home/about': typeof AppHomeHomeLayoutAboutRoute
  '/app/home/service': typeof AppHomeHomeLayoutServiceRoute
  '/app/home': typeof AppHomeHomeLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/404': typeof R404Route
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/app/home/_homeLayout': typeof AppHomeHomeLayoutRouteWithChildren
  '/_layout/app/posts/$postId': typeof LayoutAppPostsPostIdRoute
  '/app/home/_homeLayout/about': typeof AppHomeHomeLayoutAboutRoute
  '/app/home/_homeLayout/service': typeof AppHomeHomeLayoutServiceRoute
  '/app/home/_homeLayout/': typeof AppHomeHomeLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/404'
    | '/'
    | '/app/home'
    | '/app/posts/$postId'
    | '/app/home/about'
    | '/app/home/service'
    | '/app/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/'
    | '/app/posts/$postId'
    | '/app/home/about'
    | '/app/home/service'
    | '/app/home'
  id:
    | '__root__'
    | '/404'
    | '/_layout'
    | '/_layout/'
    | '/app/home/_homeLayout'
    | '/_layout/app/posts/$postId'
    | '/app/home/_homeLayout/about'
    | '/app/home/_homeLayout/service'
    | '/app/home/_homeLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  LayoutRoute: typeof LayoutRouteWithChildren
  AppHomeHomeLayoutRoute: typeof AppHomeHomeLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/app/home/_homeLayout': {
      id: '/app/home/_homeLayout'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeHomeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home/_homeLayout/': {
      id: '/app/home/_homeLayout/'
      path: '/'
      fullPath: '/app/home/'
      preLoaderRoute: typeof AppHomeHomeLayoutIndexRouteImport
      parentRoute: typeof AppHomeHomeLayoutRoute
    }
    '/app/home/_homeLayout/service': {
      id: '/app/home/_homeLayout/service'
      path: '/service'
      fullPath: '/app/home/service'
      preLoaderRoute: typeof AppHomeHomeLayoutServiceRouteImport
      parentRoute: typeof AppHomeHomeLayoutRoute
    }
    '/app/home/_homeLayout/about': {
      id: '/app/home/_homeLayout/about'
      path: '/about'
      fullPath: '/app/home/about'
      preLoaderRoute: typeof AppHomeHomeLayoutAboutRouteImport
      parentRoute: typeof AppHomeHomeLayoutRoute
    }
    '/_layout/app/posts/$postId': {
      id: '/_layout/app/posts/$postId'
      path: '/app/posts/$postId'
      fullPath: '/app/posts/$postId'
      preLoaderRoute: typeof LayoutAppPostsPostIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAppPostsPostIdRoute: typeof LayoutAppPostsPostIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAppPostsPostIdRoute: LayoutAppPostsPostIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AppHomeHomeLayoutRouteChildren {
  AppHomeHomeLayoutAboutRoute: typeof AppHomeHomeLayoutAboutRoute
  AppHomeHomeLayoutServiceRoute: typeof AppHomeHomeLayoutServiceRoute
  AppHomeHomeLayoutIndexRoute: typeof AppHomeHomeLayoutIndexRoute
}

const AppHomeHomeLayoutRouteChildren: AppHomeHomeLayoutRouteChildren = {
  AppHomeHomeLayoutAboutRoute: AppHomeHomeLayoutAboutRoute,
  AppHomeHomeLayoutServiceRoute: AppHomeHomeLayoutServiceRoute,
  AppHomeHomeLayoutIndexRoute: AppHomeHomeLayoutIndexRoute,
}

const AppHomeHomeLayoutRouteWithChildren =
  AppHomeHomeLayoutRoute._addFileChildren(AppHomeHomeLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  LayoutRoute: LayoutRouteWithChildren,
  AppHomeHomeLayoutRoute: AppHomeHomeLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
