/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHomeHomeLayoutRouteImport } from './routes/app/home/_homeLayout'
import { Route as AppHomeHomeLayoutIndexRouteImport } from './routes/app/home/_homeLayout/index'
import { Route as AppHomeHomeLayoutServiceRouteImport } from './routes/app/home/_homeLayout/service'
import { Route as AppHomeHomeLayoutAboutRouteImport } from './routes/app/home/_homeLayout/about'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeHomeLayoutRoute = AppHomeHomeLayoutRouteImport.update({
  id: '/app/home/_homeLayout',
  path: '/app/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeHomeLayoutIndexRoute = AppHomeHomeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHomeHomeLayoutRoute,
} as any)
const AppHomeHomeLayoutServiceRoute =
  AppHomeHomeLayoutServiceRouteImport.update({
    id: '/service',
    path: '/service',
    getParentRoute: () => AppHomeHomeLayoutRoute,
  } as any)
const AppHomeHomeLayoutAboutRoute = AppHomeHomeLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppHomeHomeLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/app/home': typeof AppHomeHomeLayoutRouteWithChildren
  '/app/home/about': typeof AppHomeHomeLayoutAboutRoute
  '/app/home/service': typeof AppHomeHomeLayoutServiceRoute
  '/app/home/': typeof AppHomeHomeLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/app/home/about': typeof AppHomeHomeLayoutAboutRoute
  '/app/home/service': typeof AppHomeHomeLayoutServiceRoute
  '/app/home': typeof AppHomeHomeLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/app/home/_homeLayout': typeof AppHomeHomeLayoutRouteWithChildren
  '/app/home/_homeLayout/about': typeof AppHomeHomeLayoutAboutRoute
  '/app/home/_homeLayout/service': typeof AppHomeHomeLayoutServiceRoute
  '/app/home/_homeLayout/': typeof AppHomeHomeLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/app/home'
    | '/app/home/about'
    | '/app/home/service'
    | '/app/home/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/404' | '/app/home/about' | '/app/home/service' | '/app/home'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/app/home/_homeLayout'
    | '/app/home/_homeLayout/about'
    | '/app/home/_homeLayout/service'
    | '/app/home/_homeLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AppHomeHomeLayoutRoute: typeof AppHomeHomeLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home/_homeLayout': {
      id: '/app/home/_homeLayout'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeHomeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home/_homeLayout/': {
      id: '/app/home/_homeLayout/'
      path: '/'
      fullPath: '/app/home/'
      preLoaderRoute: typeof AppHomeHomeLayoutIndexRouteImport
      parentRoute: typeof AppHomeHomeLayoutRoute
    }
    '/app/home/_homeLayout/service': {
      id: '/app/home/_homeLayout/service'
      path: '/service'
      fullPath: '/app/home/service'
      preLoaderRoute: typeof AppHomeHomeLayoutServiceRouteImport
      parentRoute: typeof AppHomeHomeLayoutRoute
    }
    '/app/home/_homeLayout/about': {
      id: '/app/home/_homeLayout/about'
      path: '/about'
      fullPath: '/app/home/about'
      preLoaderRoute: typeof AppHomeHomeLayoutAboutRouteImport
      parentRoute: typeof AppHomeHomeLayoutRoute
    }
  }
}

interface AppHomeHomeLayoutRouteChildren {
  AppHomeHomeLayoutAboutRoute: typeof AppHomeHomeLayoutAboutRoute
  AppHomeHomeLayoutServiceRoute: typeof AppHomeHomeLayoutServiceRoute
  AppHomeHomeLayoutIndexRoute: typeof AppHomeHomeLayoutIndexRoute
}

const AppHomeHomeLayoutRouteChildren: AppHomeHomeLayoutRouteChildren = {
  AppHomeHomeLayoutAboutRoute: AppHomeHomeLayoutAboutRoute,
  AppHomeHomeLayoutServiceRoute: AppHomeHomeLayoutServiceRoute,
  AppHomeHomeLayoutIndexRoute: AppHomeHomeLayoutIndexRoute,
}

const AppHomeHomeLayoutRouteWithChildren =
  AppHomeHomeLayoutRoute._addFileChildren(AppHomeHomeLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AppHomeHomeLayoutRoute: AppHomeHomeLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
